# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Wybierz masę dziecka (w kg)')),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wybierz wiek dziecka w latach (0 jeśli poniżej roku)')),
                ('drug', models.TextField(verbose_name='Wybierz lek')),
                ('other_drug', models.TextField(verbose_name='Jeśli leku nie ma na liście wpisz dawkę na kg masy ciała')),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
    ]
