# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('medicine', models.TextField(blank=True, db_column='Nazwa', null=True)),
                ('age', models.TextField(blank=True, db_column='Wiek', null=True)),
                ('dose', models.TextField(blank=True, db_column='Dawka', null=True)),
            ],
            options={
                'db_table': 'leki',
            },
        ),
    ]
