# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170522_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leki',
            name='name',
        ),
    ]
