# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_leki_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={'managed': False},
        ),
    ]
