# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170522_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leki',
            options={'managed': False},
        ),
    ]
