# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170522_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wybierz wiek dziecka w latach (0 jeśli poniżej roku)')),
                ('fever', models.BooleanField()),
                ('how_long', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('symptoms', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='drugs',
            name='drug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='other_drug',
            field=models.TextField(default=0, verbose_name='Jeśli leku nie ma na liście wpisz dawkę na kg masy ciała'),
        ),
    ]
