# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170522_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug',
            field=models.TextField(),
        ),
    ]
